"""
Config module - Configuration and settings.
"""

# Legacy exports from config.py for backward compatibility
from primr.config.config import (
    AI_REPORT_MODEL,
    AI_RESEARCH_MODEL,
    EXCLUDED_SITES,
    GEMINI_API_KEY,
    GRADE_THRESHOLD_FOR_RESEARCH_REFINEMENT,
    LOGS_DIR,
    MAX_RETRIES,
    MAX_SCRAPE_RETRIES,
    NUM_SEARCH_RESULTS,
    OUTPUT_DIR,
    PROJECT_ROOT,
    SCRAPE_MAX_DEPTH,
    SCRAPE_TIMEOUT,
    SEARCH_API_KEY,
    SEARCH_ENGINE_ID,
    WORKING_DIR,
    XAI_API_KEY,
)
from primr.config.sections_config import SECTION_KEY_MAP
from primr.config.settings import (
    AIConfig,
    APIConfig,
    CacheConfig,
    OutputConfig,
    PathConfig,
    PricingConfig,
    ScrapingConfig,
    SearchConfig,
    Settings,
    TimeoutConfig,
    configure,
    get_settings,
    reset_settings,
)

__all__ = [
    "AI_REPORT_MODEL",
    "AI_RESEARCH_MODEL",
    "EXCLUDED_SITES",
    "GEMINI_API_KEY",
    "GRADE_THRESHOLD_FOR_RESEARCH_REFINEMENT",
    "LOGS_DIR",
    "MAX_RETRIES",
    "MAX_SCRAPE_RETRIES",
    "NUM_SEARCH_RESULTS",
    "OUTPUT_DIR",
    "PROJECT_ROOT",
    "SCRAPE_MAX_DEPTH",
    "SCRAPE_TIMEOUT",
    "SEARCH_API_KEY",
    "SEARCH_ENGINE_ID",
    "SECTION_KEY_MAP",
    "WORKING_DIR",
    "XAI_API_KEY",
    "AIConfig",
    "APIConfig",
    "CacheConfig",
    "OutputConfig",
    "PathConfig",
    "PricingConfig",
    "ScrapingConfig",
    "SearchConfig",
    "Settings",
    "TimeoutConfig",
    "configure",
    "get_settings",
    "reset_settings",
]
