"""Curated OpenRouter model rows kept outside the central registry ratchet."""

from collections.abc import Callable
from typing import TypeVar

_ModelConfig = TypeVar("_ModelConfig")


def build_openrouter_models(
    model_config_type: Callable[..., _ModelConfig],
) -> tuple[_ModelConfig, ...]:
    """Build gateway-qualified rows without importing the registry module."""

    return (
        # Preserved at indices 0, 1, 2 for backwards compatibility
        model_config_type(
            name="google/gemini-2.5-flash-lite",
            display_name="OpenRouter: Gemini 2.5 Flash Lite",
            provider="openrouter",
            cost_per_1m_input_tokens=0.10,
            cost_per_1m_output_tokens=0.40,
            max_input_tokens=1_048_576,
            max_output_tokens=65_535,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.01,
        ),
        model_config_type(
            name="openai/gpt-4.1-mini",
            display_name="OpenRouter: GPT-4.1 Mini",
            provider="openrouter",
            cost_per_1m_input_tokens=0.40,
            cost_per_1m_output_tokens=1.60,
            max_input_tokens=1_047_576,
            max_output_tokens=32_768,
            supports_thinking=False,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.10,
        ),
        model_config_type(
            name="deepseek/deepseek-v3.2",
            display_name="OpenRouter: DeepSeek V3.2",
            provider="openrouter",
            cost_per_1m_input_tokens=0.269,
            cost_per_1m_output_tokens=0.40,
            max_input_tokens=163_840,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=False,
            cost_per_1m_input_tokens_cached=0.1345,
        ),
        # Google Gemini additions
        model_config_type(
            name="google/gemini-3.8-flash",
            display_name="OpenRouter: Gemini 3.8 Flash",
            provider="openrouter",
            cost_per_1m_input_tokens=0.75,
            cost_per_1m_output_tokens=3.75,
            max_input_tokens=1_048_576,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.075,
        ),
        model_config_type(
            name="google/gemini-3.7-flash",
            display_name="OpenRouter: Gemini 3.7 Flash",
            provider="openrouter",
            cost_per_1m_input_tokens=0.75,
            cost_per_1m_output_tokens=3.75,
            max_input_tokens=1_048_576,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.075,
        ),
        model_config_type(
            name="google/gemini-3.1-flash-lite",
            display_name="OpenRouter: Gemini 3.1 Flash Lite",
            provider="openrouter",
            cost_per_1m_input_tokens=0.25,
            cost_per_1m_output_tokens=1.50,
            max_input_tokens=1_048_576,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.025,
        ),
        # OpenAI additions
        model_config_type(
            name="openai/gpt-5.4-mini",
            display_name="OpenRouter: GPT-5.4 Mini",
            provider="openrouter",
            cost_per_1m_input_tokens=0.75,
            cost_per_1m_output_tokens=4.50,
            max_input_tokens=400_000,
            max_output_tokens=128_000,
            supports_thinking=False,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.075,
        ),
        model_config_type(
            name="openai/gpt-5.4-nano",
            display_name="OpenRouter: GPT-5.4 Nano",
            provider="openrouter",
            cost_per_1m_input_tokens=0.20,
            cost_per_1m_output_tokens=1.25,
            max_input_tokens=400_000,
            max_output_tokens=128_000,
            supports_thinking=False,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.02,
        ),
        # DeepSeek additions
        model_config_type(
            name="deepseek/deepseek-chat",
            display_name="OpenRouter: DeepSeek Chat",
            provider="openrouter",
            cost_per_1m_input_tokens=0.27,
            cost_per_1m_output_tokens=0.40,
            max_input_tokens=163_840,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=False,
            cost_per_1m_input_tokens_cached=0.07,
        ),
        model_config_type(
            name="deepseek/deepseek-r1",
            display_name="OpenRouter: DeepSeek R1",
            provider="openrouter",
            cost_per_1m_input_tokens=0.55,
            cost_per_1m_output_tokens=2.19,
            max_input_tokens=163_840,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=False,
            cost_per_1m_input_tokens_cached=0.14,
        ),
        # Anthropic additions
        model_config_type(
            name="anthropic/claude-sonnet-4.6",
            display_name="OpenRouter: Claude Sonnet 4.6",
            provider="openrouter",
            cost_per_1m_input_tokens=3.00,
            cost_per_1m_output_tokens=15.00,
            max_input_tokens=1_000_000,
            max_output_tokens=64_000,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.30,
        ),
        model_config_type(
            name="anthropic/claude-haiku-4.5",
            display_name="OpenRouter: Claude Haiku 4.5",
            provider="openrouter",
            cost_per_1m_input_tokens=1.00,
            cost_per_1m_output_tokens=5.00,
            max_input_tokens=200_000,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.10,
        ),
        model_config_type(
            name="anthropic/claude-3.7-sonnet",
            display_name="OpenRouter: Claude 3.7 Sonnet",
            provider="openrouter",
            cost_per_1m_input_tokens=3.00,
            cost_per_1m_output_tokens=15.00,
            max_input_tokens=1_000_000,
            max_output_tokens=64_000,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.30,
        ),
        model_config_type(
            name="anthropic/claude-3.5-haiku",
            display_name="OpenRouter: Claude 3.5 Haiku",
            provider="openrouter",
            cost_per_1m_input_tokens=1.00,
            cost_per_1m_output_tokens=5.00,
            max_input_tokens=200_000,
            max_output_tokens=65_536,
            supports_thinking=True,
            supports_tools=True,
            supports_multimodal=True,
            cost_per_1m_input_tokens_cached=0.10,
        ),
        # Meta additions
        model_config_type(
            name="meta-llama/llama-3.3-70b-instruct",
            display_name="OpenRouter: Llama 3.3 70B Instruct",
            provider="openrouter",
            cost_per_1m_input_tokens=0.12,
            cost_per_1m_output_tokens=0.30,
            max_input_tokens=131_072,
            max_output_tokens=8_192,
            supports_thinking=False,
            supports_tools=True,
            supports_multimodal=False,
            cost_per_1m_input_tokens_cached=0.06,
        ),
    )
