"""
Utils module - Logging, console output, and utility functions.
"""

from primr.utils.async_utils import (
    AsyncBridge,
    configure_executor,
    ensure_async,
    ensure_sync,
    gather_with_concurrency,
    is_async_context,
    run_async,
    run_async_with_timeout,
    run_sync,
    run_sync_new_loop,
    shutdown_executor,
    sync_context,
)
from primr.utils.chat_logger import log_chat_interaction
from primr.utils.config_validation import (
    ConfigError,
    ConfigValidationResult,
    PrimrConfig,
    export_schema,
    load_config,
    require_valid_config,
    reset_config,
    validate_config,
)
from primr.utils.console import Console, console, get_console, set_console
from primr.utils.errors import (
    AIError,
    AuthenticationError,
    ConfigurationError,
    ErrorContext,
    OutputError,
    PermanentError,
    PrimrConfigurationError,
    # Typed error hierarchy (preferred for new code)
    PrimrError,
    PrimrValidationError,
    QuotaError,
    ResearchError,
    RetryConfig,
    ScrapingError,
    SearchError,
    TransientError,
    TypedNetworkError,
    TypedRateLimitError,
    ValidationError,
    async_safe_callback,
    calculate_backoff_delay,
    error_context,
    retry_on_failure,
    safe_call,
)
from primr.utils.files import (
    ensure_parent_exists,
    get_cache_key,
    get_cache_path,
    get_company_folder,
    get_safe_path,
    sanitize_filename,
    secure_temp_dir,
    secure_temp_file,
    validate_directory_exists,
    validate_file_exists,
)
from primr.utils.formatting import (
    clean_content,
    format_currency,
    format_number,
    remove_em_dashes,
    remove_emojis,
)
from primr.utils.logging_config import (
    LogContext,
    get_logger,
    setup_logging,
)
from primr.utils.observability import (
    Metrics,
    OperationContext,
    emit_metrics,
    get_correlation_id,
    operation_context,
    set_correlation_id,
    timed,
    tracked_operation,
)
from primr.utils.resources import (
    BoundedCache,
    CacheMetrics,
    ThreadSafeSingleton,
    managed_http_client,
    managed_temp_dir,
    managed_temp_file,
)
from primr.utils.retry import (
    RetryAttempt,
    RetryPolicy,
    RetryPolicyManager,
)
from primr.utils.security import (
    SecurityAuditLogger,
    generate_secure_id,
    generate_secure_token,
    get_secret_from_env,
    hash_secret,
    mask_dict_values,
    mask_sensitive_data,
    sanitize_log_input,
    secure_compare,
    verify_hashed_secret,
)
from primr.utils.type_guards import (
    TypeValidationError,
    is_valid_type,
    validate_api_response,
    validate_dataclass,
    validate_type,
)
from primr.utils.validators import (
    InputValidationError,
    safe_json_get,
    safe_json_parse,
    sanitize_for_filename,
    validate_company_name,
    validate_file_path,
    validate_url,
)

__all__ = [
    # Async utilities
    "run_sync",
    "run_sync_new_loop",
    "run_async",
    "run_async_with_timeout",
    "ensure_async",
    "ensure_sync",
    "sync_context",
    "AsyncBridge",
    "is_async_context",
    "gather_with_concurrency",
    "configure_executor",
    "shutdown_executor",
    # Configuration validation
    "ConfigError",
    "ConfigValidationResult",
    "PrimrConfig",
    "load_config",
    "validate_config",
    "require_valid_config",
    "reset_config",
    "export_schema",
    # Console
    "Console",
    "console",
    "get_console",
    "set_console",
    # Legacy errors (deprecated - use typed hierarchy)
    "ResearchError",
    "ConfigurationError",
    "ScrapingError",
    "AIError",
    "SearchError",
    "OutputError",
    "ValidationError",
    "safe_call",
    "retry_on_failure",
    "ErrorContext",
    "RetryConfig",
    "calculate_backoff_delay",
    "error_context",
    "async_safe_callback",
    # Typed error hierarchy (preferred for new code)
    "PrimrError",
    "TransientError",
    "PermanentError",
    "TypedRateLimitError",
    "QuotaError",
    "TypedNetworkError",
    "PrimrValidationError",
    "AuthenticationError",
    "PrimrConfigurationError",
    # Retry Policy Manager
    "RetryPolicy",
    "RetryAttempt",
    "RetryPolicyManager",
    # Logging
    "setup_logging",
    "get_logger",
    "LogContext",
    "log_chat_interaction",
    # Files
    "secure_temp_file",
    "secure_temp_dir",
    "sanitize_filename",
    "get_safe_path",
    "get_company_folder",
    "get_cache_key",
    "get_cache_path",
    "validate_file_exists",
    "validate_directory_exists",
    "ensure_parent_exists",
    # Formatting
    "clean_content",
    "format_number",
    "format_currency",
    "remove_emojis",
    "remove_em_dashes",
    # Type Guards
    "TypeValidationError",
    "validate_type",
    "validate_dataclass",
    "validate_api_response",
    "is_valid_type",
    # Resources
    "managed_temp_file",
    "managed_temp_dir",
    "managed_http_client",
    "BoundedCache",
    "CacheMetrics",
    "ThreadSafeSingleton",
    # Observability
    "get_correlation_id",
    "set_correlation_id",
    "OperationContext",
    "operation_context",
    "timed",
    "Metrics",
    "emit_metrics",
    "tracked_operation",
    # Security
    "secure_compare",
    "hash_secret",
    "verify_hashed_secret",
    "mask_sensitive_data",
    "mask_dict_values",
    "SecurityAuditLogger",
    "sanitize_log_input",
    "generate_secure_token",
    "generate_secure_id",
    "get_secret_from_env",
    # Validators
    "InputValidationError",
    "validate_url",
    "validate_file_path",
    "validate_company_name",
    "sanitize_for_filename",
    "safe_json_parse",
    "safe_json_get",
]
